apiVersion: v1
kind: Service
metadata:
  name: servico-aplicacao
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80  # Certifique-se que corresponde ao containerPort
  selector:
    app: aplicacao-pod
  externalTrafficPolicy: Local